# Variables that can be put on the x and y axes
         
axis_vars <- c(
  "Latitude" = "lat",                           
  "Longitude" = "lon",                           
  "Mean temperature (celsius)" =  "mean.temp",                     
  "Sum precipitation (cm)" = "sum.precip",                    
  "SD temperature (celsius)" = "sd.temp",                       
  "Growing season" = "growing.season",        
  "Total population (log) " = "pop_log",                       
  "Morphological complexity" = "morphological.complexity",
  "Complexity bias"= "complexity.bias",               
  "Complexity bias (partialing out frequency)" = "p.complexity.bias",             
  "Complexity bias (monomorphemic words only)" = "mono.complexity.bias",          
  "Complexity bias (open class words only)" = "open.complexity.bias",          
  "Lexical diversity (ZM law parameters)" = "scaled.LDT.ZM",                 
  "Lexical diversity (entropy)" = "scaled.LDT.H",                 
  "Lexical diversity (type-token ratio)" = "scaled.LDT.TTR",                
  "Mean length"= "mean.length",                   
  "Mean dependency length" = "mean.dependency.length",        
  "Information density" = "information.density",           
  "Syllable rate" =  "syllable.rate",                 
  "Information rate" = "information.rate",              
  "Mean AoA" = "mean.aoa",                      
  "Vowel diversity" = "normalized.vowel.diversity",    
  "Consonant diversity" = "normalized.consonant.diversity",
  "Tone diversity" = "normalized.tone.diversity",     
  "Phoneme diversity" =  "normalized.phoneme.diversity",  
  "Distance from origin" =  "distance.from.origin",          
  "Area (log)" =  "area_log",                      
  "Perimeter (log)" =  "perimeter_log",                 
  "Number of ling neighbors (log)" =  "n.neighbors_log",               
  "SD precipitation (cm; log)" = "sd.precip_log",                 
  "Ratio L2:L1 (log)" =  "ratio.L2.L1_log",               
  "Number L1 speakers (log)" =  "n.L1.speakers_log",             
  "Number L2 speakers (log)" =  "n.L2.speakers_log",             
  "Number phonemes (log)" =  "n.phonemes_log",                
  "Number consonants (log)" =  "n.consonants_log",              
  "Number voewls (log)" =  "n.vowels_log",                  
  "Number sonorants (log)" =  "n.sonorants_log",              
  "Number obstruents (log)" =  "n.obstruents_log",              
  "Number monophthongs (log)" = "n.monophthongs_log",            
  "Number q. monophthongs (log)" = "n.qual.monophthongs_log",       
  "Number tones (log)" =  "n.tones_log"
  )